server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8

spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: test
    password: 1234
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create # update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

jwt:
  secret: d12lk3lkjdslfkjlk23jlkjasdfo9azxcvpqowuemnbzxcqw70m4534asdjldasd19dkslfjafdjlk23jlweiob01askdhq

#    open-in-view: true
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    show-sql: true
#    properties:
#      '[hibernate.format_sql]': true
#
#  output:
#    ansi:
#      enabled: always
