spring:
  profiles:
    default: dev

#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#    show-sql: true

logging:
  config: classpath:log4j2.xml
